micronaut:
  application:
    name: myapp
  server:
    port: 8080

datasources:
  default:
#    url: ${JDBC_URL:`jdbc:h2:mem:project_arth;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

    url: jdbc:mysql://127.0.0.1:3306/project_arth?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: admin
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
---
jpa:
  default:
    packages-to-scan:
      - 'com.decipherx.projectarth.webapp.domain'
  properties:
    hibernate:
      hbm2ddl:
        auto: update
      show_sql: true
---